# Generated by Django 5.2 on 2025-04-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorciado', 'Divorciado')], max_length=10)),
                ('orientacion_sexual', models.CharField(choices=[('Heterosexual', 'Heterosexual'), ('Bisexual', 'Bisexual'), ('Homosexual', 'Homosexual')], max_length=12)),
                ('uso_proteccion', models.BooleanField()),
                ('consumo_drogas', models.BooleanField()),
                ('n_parejas_sexuales', models.PositiveIntegerField()),
                ('historial_its', models.BooleanField()),
                ('nivel_socioeconomico', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=10)),
                ('cantidad_tatuajes', models.PositiveIntegerField()),
                ('cantidad_donaciones_dadas', models.PositiveIntegerField()),
                ('cantidad_donaciones_recibidas', models.PositiveIntegerField()),
                ('resultado_prediccion', models.BooleanField(blank=True, null=True)),
                ('porcentaje_confianza', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
